---
title: "Untitled"
author: "Andrew W. Park"
date: '2022-10-26'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




## Required packages
```{r loadLibs}
library(dplyr)
library(maptools)
library(raster)
library(metacom)
```


```{r loadData}
load("get_db.Rda")
```






## Creating Centroids for WMAs
```{r wmaLatLong}

centroids <- db |> 
  group_by(Site) |> 
  summarize(cLat=mean(Lat),cLon=mean(Long))

```





```{r}

sites <- unique(db$Site)
sub.db <- db[,11:62]

#for loop that outputs interaction matrix combining all years
ret <- matrix(0, ncol= 52, nrow=length(sites)) 
latitude=vector(); longitude=vector()
for(i in 1:length(sites)){
  temp=sub.db[which(db$Site==sites[i]),]	
  ret[i,] = colSums(temp)
  latitude[i] = mean(db[which(db$Site == sites[i]),'Lat'])
  longitude[i] = mean(db[which(db$Site == sites[i]),'Long'])
}
rownames(ret)=sites; colnames(ret)=colnames(sub.db)

#ret.lat=ret[order(latitude),]
ret.nozero <- ret[-which(rowSums(ret) == 0),]
ret.nozero <- ret.nozero > 0 
sites.nozero <- sites[-which(rowSums(ret)==0)]
latitude <- latitude[-which(rowSums(ret)==0)]
longitude <- longitude[-which(rowSums(ret)==0)]

```





### Default ordering based on RA 

```{r}
#pull out site scores from reciprocal averaging
scores <- OrderMatrix(ret.nozero, scores=1, outputScores=TRUE)

#Coherence 
coh.ret.nozero <- Coherence(ret.nozero > 0, order=TRUE, orderNulls=TRUE)
#Species Turnover
turn.ret.nozero <- Turnover(ret.nozero > 0, order=TRUE, orderNulls=TRUE)
#Boundary clumping
clump.ret.nozero <- BoundaryClump(ret.nozero > 0, order=TRUE)

```







### Spatial ordering

```{r}
ret.spatial <- ret.nozero[order(latitude),order(scores$speciesscores)]

#Coherence 
coh.ret.spatial <- Coherence(ret.spatial > 0, order=FALSE, sims=100, orderNulls=TRUE)
#Species Turnover
turn.ret.spatial <- Turnover(ret.spatial > 0, order=FALSE, orderNulls=TRUE)
#Boundary clumping
clump.ret.spatial <- BoundaryClump(ret.spatial > 0, order=FALSE)

```




















```{r}
####### FOR PPT AND MEAN TEMP THE ANNUAL VALUES SHOULD COMPARE EXACTLY WITH PRISM ##########
ppt <- readAsciiGrid("../prism/prism_worldclim/PRISM_ppt_stable_4kmM2_2009_asc.asc",as.image=F)
tmean <- readAsciiGrid("PRISM_tmean_stable_4kmM2_2009_asc.asc",as.image=F)
######## PRECIPITATION ###########
r.ppt <- raster(ppt)
r.ppt <- crop(r.ppt,extent(c(-94,-80,24.5,36)))
prism.ppt <- extract(r.ppt,cbind(met.data$lon,met.data$lat))

```

