---
title: "Untitled"
author: "Andrew W. Park"
date: '2022-11-18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loadLibs}
library(magrittr)
library(tidyverse)
library(patchwork)
```

```{r loadData}
load("get_finalAnalysis.Rda")
source(knitr::purl("diseaseKernel.Rmd", quiet=TRUE))
load("get_siteData.Rda") #load this last as another script temporarily uses value 'sites'
```

```{r combine}
# sites have enviro data, disease data and culic score data

# start with sites df (enviro data) and add disease data
hdDens <- raster::extract(r,cbind(sites$lon,sites$lat))
sites %<>% mutate(hdDens=hdDens)

#now ad culic score data
siteScores <- unlist(scores[[2]], recursive = TRUE, use.names = TRUE)
sc <- tibble(
  names(siteScores),
  unname(siteScores)
)

sc %<>% rename(Site=`names(siteScores)`,score=`unname(siteScores)`)
sites %<>% left_join(.,sc)
sites %<>% drop_na(score)

sites %<>% mutate(scorePos=score-min(score))
sites %<>% mutate(scoreSqrt=sqrt(scorePos))
sites %<>% mutate(scoreRank=rank(score,ties.method="first"))

```

```{r ordinated}
# create ordinated matrix for plotting
om <- metacom::OrderMatrix(ret.nozero) 

omBoundaries <- tibble(first1=numeric(0),last1=numeric(0))

om <- t(om)

for (i in 1:dim(om)[1]){
  pres <- which(om[i,]==1)
  first1 <- min(pres)
  last1 <- max(pres)
  omBoundaries %<>% add_case(first1=first1,last1=last1)
}

om2 <- matrix(rep(0,dim(om)[1]*dim(om)[2]),nrow=dim(om)[1])
for (i in 1:dim(om2)[1]){
  for (j in as.numeric(omBoundaries[i,1]):as.numeric(omBoundaries[i,2])){
    om2[i,j] <- 1
  }
}

om2 %<>% as_tibble(.)
om2 %<>% mutate(sp=1:dim(om2)[1])
om2 %<>% pivot_longer(starts_with("V"),names_to="site",values_to="pres")

levelSites <- c(paste("V",1:212,sep=""))
levelSp <- 1:52
om2 %<>% mutate(site=factor(site,levels=levelSites))
om2 %<>% mutate(sp=factor(sp,levels=levelSp))
p.ss <- om2 %>% ggplot(.,aes(x=site,y=sp))+geom_tile(aes(fill=as.factor(pres)))+scale_fill_manual(name="Presence",values=c("gray90","gray20"))+xlab("")+ylab("Species\nrange")+theme(axis.text.x=element_blank(),axis.ticks.x=element_blank(),axis.text.y=element_blank(),axis.ticks.y=element_blank())+theme(legend.position="none")


```




```{r}
#exploratory plots

p1 <- sites %>% ggplot(.,aes(x=scoreRank,y=elev))+geom_point()+geom_smooth(span=1.0)+xlab("")+theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+ylab("Elevation\n(m)")
p2 <- sites %>% ggplot(.,aes(x=scoreRank,y=prism.ppt))+geom_point()+geom_smooth(span=1.0)+xlab("")+theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+ylab("Precipitation\n(mm)")
p3 <- sites %>% ggplot(.,aes(x=scoreRank,y=prism.tmean))+geom_point()+geom_smooth(span=1.0)+xlab("Sites")+theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+ylab("Mean\ntemp (C)")
p4 <- sites %>% ggplot(.,aes(x=scoreRank,y=prism.trange))+geom_point()+geom_smooth(span=1.0)+xlab("")+theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+ylab("Temp\nrange (C)")
p5 <- sites %>% ggplot(.,aes(x=scoreRank,y=hdDens))+geom_point()+geom_smooth(span=1.0)+xlab("")+theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+ylab("Kernel density\ndisease reports")

png("test.png",width=400,height=600)
p5/p.ss/p2/p4/p1/p3
dev.off()




```


```{r gam}

sites %>% ggplot(.,aes(x=score))+geom_histogram()
sites %>% ggplot(.,aes(x=scoreSqrt))+geom_histogram()
sites %>% ggplot(.,aes(x=log(score+5)))+geom_histogram()


myGam1 <- mgcv::gam(scoreSqrt~s(lon,lat)+
                      prism.ppt+
                      prism.tmean+
                      prism.trange+
                      elev
                    ,family=gaussian,data=sites)



```


```{r}
### DO THE GBM
library(gbm)
library(cowplot)
my.gbm<- gbm(scoreSqrt~lat+lon+prism.ppt+prism.tmean+prism.tmin+prism.tmax+prism.trange+elev,
            data=sites, distribution="gaussian",n.trees=50000,shrinkage=0.001,interaction.depth=5,bag.fraction=0.70,train.fraction=0.8,n.minobsinnode=5,cv.folds=5,keep.data=TRUE,verbose=TRUE)
summary(my.gbm)

### PARTIAL DEPENDENCIES
##### 1. temp range
best.iter <- gbm.perf(my.gbm,method="cv")
inv<-pdp::partial(my.gbm,n.trees=best.iter,"prism.trange")

plot1 <- inv %>%
  na.omit() %>%
  ggplot() +
  geom_line(aes(x = prism.trange, y = yhat),color="black",size=1) +
  xlim(min(sites$prism.trange),max(sites$prism.trange))+
  ylab(" ") +
  theme_minimal() +
  theme(axis.title.x = element_blank())+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),axis.text=element_text(size=12))

plot2 <- sites %>%
  dplyr::select(prism.trange) %>%
  na.omit() %>%
  ggplot(aes(prism.trange)) +
  geom_histogram(breaks=seq(min(sites$prism.trange),max(sites$prism.trange), by = 1),fill="gray") +
  scale_y_continuous(position = "right")+
  ylab("") +
  theme_minimal() +
  theme(axis.title.x = element_blank(),axis.text=element_text(size=12))

p1 <- add_sub(plot1," ")
p2 <- add_sub(plot2,"Temperature range (C)",size=12)
p.tRange<-ggdraw() +
  draw_plot(p2,x=0.05,scale=0.95) +
  draw_plot(p1,x=-0.04,scale=0.975,y=0.05) 

###### 2. min temp
inv<-pdp::partial(my.gbm,n.trees=best.iter,"prism.tmin")

plot1 <- inv %>%
  na.omit() %>%
  ggplot() +
  geom_line(aes(x = prism.tmin, y = yhat),color="black",size=1) +
  xlim(min(sites$prism.tmin),max(sites$prism.tmin))+
  ylab(" ") +
  theme_minimal() +
  theme(axis.title.x = element_blank())+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),axis.text=element_text(size=12))

plot2 <- sites %>%
  dplyr::select(prism.tmin) %>%
  na.omit() %>%
  ggplot(aes(prism.tmin)) +
  geom_histogram(breaks=seq(min(sites$prism.tmin),max(sites$prism.tmin), by = 1),fill="gray") +
  scale_y_continuous(position = "right")+
  ylab("") +
  theme_minimal() +
  theme(axis.title.x = element_blank(),axis.text=element_text(size=12))

p1 <- add_sub(plot1," ")
p2 <- add_sub(plot2,"Min. Temp. (C)",size=12)
p.tMin<-ggdraw() +
  draw_plot(p2,x=0.05,scale=0.95) +
  draw_plot(p1,x=-0.04,scale=0.975,y=0.05) 

###### 3. mean temp
inv<-pdp::partial(my.gbm,n.trees=best.iter,"prism.tmean")

plot1 <- inv %>%
  na.omit() %>%
  ggplot() +
  geom_line(aes(x = prism.tmean, y = yhat),color="black",size=1) +
  xlim(min(sites$prism.tmean),max(sites$prism.tmean))+
  ylab(" ") +
  theme_minimal() +
  theme(axis.title.x = element_blank())+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),axis.text=element_text(size=12))

plot2 <- sites %>%
  dplyr::select(prism.tmean) %>%
  na.omit() %>%
  ggplot(aes(prism.tmean)) +
  geom_histogram(breaks=seq(min(sites$prism.tmean),max(sites$prism.tmean), by = 0.5),fill="gray") +
  scale_y_continuous(position = "right")+
  ylab("") +
  theme_minimal() +
  theme(axis.title.x = element_blank(),axis.text=element_text(size=12))

p1 <- add_sub(plot1," ")
p2 <- add_sub(plot2,"Mean Temp. (C)",size=12)
p.tMean<-ggdraw() +
  draw_plot(p2,x=0.05,scale=0.95) +
  draw_plot(p1,x=-0.04,scale=0.975,y=0.05) 


###### 4. lat
inv<-pdp::partial(my.gbm,n.trees=best.iter,"lat")

plot1 <- inv %>%
  na.omit() %>%
  ggplot() +
  geom_line(aes(x = lat, y = yhat),color="black",size=1) +
  xlim(min(sites$lat),max(sites$lat))+
  ylab(" ") +
  theme_minimal() +
  theme(axis.title.x = element_blank())+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),axis.text=element_text(size=12))

plot2 <- sites %>%
  dplyr::select(lat) %>%
  na.omit() %>%
  ggplot(aes(lat)) +
  geom_histogram(breaks=seq(min(sites$lat),max(sites$lat), by = 0.5),fill="gray") +
  scale_y_continuous(position = "right")+
  ylab("") +
  theme_minimal() +
  theme(axis.title.x = element_blank(),axis.text=element_text(size=12))

p1 <- add_sub(plot1," ")
p2 <- add_sub(plot2,"Latitude",size=12)
p.lat<-ggdraw() +
  draw_plot(p2,x=0.05,scale=0.95) +
  draw_plot(p1,x=-0.04,scale=0.975,y=0.05) 


###### 5. lon
inv<-pdp::partial(my.gbm,n.trees=best.iter,"lon")

plot1 <- inv %>%
  na.omit() %>%
  ggplot() +
  geom_line(aes(x = lon, y = yhat),color="black",size=1) +
  xlim(min(sites$lon),max(sites$lon))+
  ylab(" ") +
  theme_minimal() +
  theme(axis.title.x = element_blank())+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),axis.text=element_text(size=12))

plot2 <- sites %>%
  dplyr::select(lon) %>%
  na.omit() %>%
  ggplot(aes(lon)) +
  geom_histogram(breaks=seq(min(sites$lon),max(sites$lon), by = 1),fill="gray") +
  scale_y_continuous(position = "right")+
  ylab("") +
  theme_minimal() +
  theme(axis.title.x = element_blank(),axis.text=element_text(size=12))

p1 <- add_sub(plot1," ")
p2 <- add_sub(plot2,"Longitude",size=12)
p.lon<-ggdraw() +
  draw_plot(p2,x=0.05,scale=0.95) +
  draw_plot(p1,x=-0.04,scale=0.975,y=0.05) 


###### 6. precip
inv<-pdp::partial(my.gbm,n.trees=best.iter,"prism.ppt")

plot1 <- inv %>%
  na.omit() %>%
  ggplot() +
  geom_line(aes(x = prism.ppt, y = yhat),color="black",size=1) +
  xlim(min(sites$prism.ppt),max(sites$prism.ppt))+
  ylab(" ") +
  theme_minimal() +
  theme(axis.title.x = element_blank())+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),axis.text=element_text(size=12))

plot2 <- sites %>%
  dplyr::select(prism.ppt) %>%
  na.omit() %>%
  ggplot(aes(prism.ppt)) +
  geom_histogram(breaks=seq(min(sites$prism.ppt),max(sites$prism.ppt), by = 100),fill="gray") +
  scale_y_continuous(position = "right")+
  ylab("") +
  theme_minimal() +
  theme(axis.title.x = element_blank(),axis.text=element_text(size=12))

p1 <- add_sub(plot1," ")
p2 <- add_sub(plot2,"Precipitation (mm)",size=12)
p.prismPpt<-ggdraw() +
  draw_plot(p2,x=0.05,scale=0.95) +
  draw_plot(p1,x=-0.04,scale=0.975,y=0.05) 

###### 7. elev
inv<-pdp::partial(my.gbm,n.trees=best.iter,"elev")

plot1 <- inv %>%
  na.omit() %>%
  ggplot() +
  geom_line(aes(x = elev, y = yhat),color="black",size=1) +
  xlim(min(sites$elev),max(sites$elev))+
  ylab(" ") +
  theme_minimal() +
  theme(axis.title.x = element_blank())+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),axis.text=element_text(size=12))

plot2 <- sites %>%
  dplyr::select(elev) %>%
  na.omit() %>%
  ggplot(aes(elev)) +
  geom_histogram(breaks=seq(min(sites$elev),max(sites$elev), by = 10),fill="gray") +
  scale_y_continuous(position = "right")+
  ylab("") +
  theme_minimal() +
  theme(axis.title.x = element_blank(),axis.text=element_text(size=12))

p1 <- add_sub(plot1," ")
p2 <- add_sub(plot2,"Elevation (m)",size=12)
p.elev<-ggdraw() +
  draw_plot(p2,x=0.05,scale=0.95) +
  draw_plot(p1,x=-0.04,scale=0.975,y=0.05) 


###### 8. maxTemp
inv<-pdp::partial(my.gbm,n.trees=best.iter,"prism.tmax")

plot1 <- inv %>%
  na.omit() %>%
  ggplot() +
  geom_line(aes(x = prism.tmax, y = yhat),color="black",size=1) +
  xlim(min(sites$prism.tmax),max(sites$prism.tmax))+
  ylab(" ") +
  theme_minimal() +
  theme(axis.title.x = element_blank())+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),axis.text=element_text(size=12))

plot2 <- sites %>%
  dplyr::select(prism.tmax) %>%
  na.omit() %>%
  ggplot(aes(prism.tmax)) +
  geom_histogram(breaks=seq(min(sites$prism.tmax),max(sites$prism.tmax), by =0.5),fill="gray") +
  scale_y_continuous(position = "right")+
  ylab("") +
  theme_minimal() +
  theme(axis.title.x = element_blank(),axis.text=element_text(size=12))

p1 <- add_sub(plot1," ")
p2 <- add_sub(plot2,"Max. Temp. (C)",size=12)
p.tMax<-ggdraw() +
  draw_plot(p2,x=0.05,scale=0.95) +
  draw_plot(p1,x=-0.04,scale=0.975,y=0.05) 


png("pd.png",height=800,width=600)
(p.tRange|p.tMin)/(p.tMean|p.lat)/(p.lon|p.prismPpt)/(p.elev|p.tMax)
dev.off()

### RELATIVE INFLUENCE PLOT
par(mfrow=c(1,1))
gbm_full_summary = summary.gbm(my.gbm)

gbm_summary_idx = which(gbm_full_summary$rel.inf > 1)

gbm_full_short = gbm_full_summary[gbm_summary_idx,]

gbm_full_short$var = as.character(gbm_full_short$var)

png("relInf.png")
colors = ifelse(rev(gbm_full_short$rel.inf) >= 2,'gray','snow4')
par(mfrow=c(1,1),
    mar=c(5,10,4,2)+0.1)
bar = barplot(rev(gbm_full_short$rel.inf),
              horiz = TRUE,
              xlim = c(0,30),
              xlab = 'Percent Relative Influence',
              col = colors )


axis(2,
     at = bar,
     labels=rev(c('Temp. range (C)', 'Min. temp. (C)', 'Mean temp. (C)', 'Lat.', 'Lon.', 'Precip. (mm)', 'Elevation (m)', 'Max. temp. (C)'  )),las = 2)
dev.off()


#### MODEL PERFORMANCE
preds = predict.gbm(dis.tree_null, dis.boost.test,
                    n.trees = dis.tree_null$gbm.call$best.trees, type = 'response')

calc.deviance(obs=dis.boost.test$dis.pres, pred = preds,
              calc.mean=TRUE)

```


```{r}
# put site x spp info in tidydata form for gg-plotting
hmap <- db %>% dplyr::select(c(3,11:62)) %>% pivot_longer(.,2:53,names_to="species",values_to="present") %>% distinct()
hmap %<>% rename(site=Site)

# add HD info
hd4merge <- sites %>% dplyr::select(Site,hdDens)
hd4merge %<>% mutate(hdScore=hdDens*1000)
hd4merge %<>% dplyr::select(-hdDens)
hd4merge %<>% rename(site=Site)
hmap %<>% left_join(.,hd4merge)

# order sites by HD-score and species by their (similarity) scores
hmap %<>% mutate(species=as.factor(species))
hmap %<>% mutate(species=fct_relevel(species,names(sort(scores$speciesscores))))
hmap %<>% mutate(site=as.factor(site))
hmap %<>% mutate(site=fct_relevel(site,hd4merge$site[order(hd4merge$hdScore)]))


# get SR at sites to remove SR=0
siteSR <- hmap %>% group_by(site) %>% summarize(sr=sum(present))
hmap %<>% left_join(.,siteSR)

#get culi site richness and consider removing rare species
culiSR <- hmap %>% group_by(species) %>% summarize(siteR=sum(present))
hmap %<>% left_join(.,culiSR)

for (i in 1:dim(hmap)[1]){
  if (hmap$present[i]==1){
    hmap$hdScore[i] <- NA
  }
}

hmap %>% dplyr::filter(sr>0 & siteR>2) %>% ggplot(.,aes(x=species,y=site,fill=hdScore))+geom_tile()+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),axis.text.y=element_blank(),axis.ticks.y=element_blank())+scale_fill_gradient(low="white", high="gray50",na.value="black")



sites %>% ggplot(.,aes(x=scoreRank,y=hdDens))+geom_point(col="gray65")+geom_smooth(col="black",se=F,span=1.2)+xlab("Sites rank by vector similarity")+ylab("Level of hemorrhagic disease reporting")+theme_minimal()

```

