---
title: "Environmental data for sites"
author: "Andrew W. Park"
date: '2022-11-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loadLibs}
library(tidyverse)
library(magrittr)
library(maptools)
library(raster)
```


```{r loadSiteCentroidData}
load("get_siteCentroids.Rda")
# file above was created from loading analysis.RData and saving only the centroids dataframe
# analysis.RData was obtained by running the initial parts of analysis.Rmd and saving the session
sites <- centroids
sites %<>% rename(lon=cLon,lat=cLat)
```


```{r}
####### FOR PPT AND MEAN TEMP THE ANNUAL VALUES SHOULD COMPARE EXACTLY WITH PRISM ##########
ppt <- maptools::readAsciiGrid("../culicoides/prism/prism_worldclim/PRISM_ppt_stable_4kmM2_2009_asc.asc",as.image=F)
tmean <- maptools::readAsciiGrid("../culicoides/prism/prism_worldclim/PRISM_tmean_stable_4kmM2_2009_asc.asc",as.image=F)
######## PRECIPITATION ###########
r.ppt <- raster::raster(ppt)
#r.ppt <- raster::crop(r.ppt,extent(c(-100,-80,24.5,43)))
prism.ppt <- raster::extract(r.ppt,cbind(sites$lon,sites$lat))
sites$prism.ppt<-prism.ppt
######### MEAN TEMP ################
r.tmean<- raster::raster(tmean)
#r.tmean<- raster::crop(r.tmean,extent(c(-100,-80,24.5,43)))
prism.tmean<- raster::extract(r.tmean,cbind(sites$lon,sites$lat))
sites$prism.tmean<-prism.tmean

######## FOR TEMP RANGE, WE NEED MONTHLY DATA SO MIN IS IN COLDEST MONTH, MAX IN WARMEST ###########
tmin.jan<-readAsciiGrid("../culicoides/prism/prism_worldclim/PRISM_tmin_stable_4kmM2_200901_asc.asc",as.image=F)
tmin.feb<-readAsciiGrid("../culicoides/prism/prism_worldclim/PRISM_tmin_stable_4kmM2_200902_asc.asc",as.image=F)
tmin.mar<-readAsciiGrid("../culicoides/prism/prism_worldclim/PRISM_tmin_stable_4kmM2_200903_asc.asc",as.image=F)
tmin.apr<-readAsciiGrid("../culicoides/prism/prism_worldclim/PRISM_tmin_stable_4kmM2_200904_asc.asc",as.image=F)
tmin.may<-readAsciiGrid("../culicoides/prism/prism_worldclim/PRISM_tmin_stable_4kmM2_200905_asc.asc",as.image=F)
tmin.jun<-readAsciiGrid("../culicoides/prism/prism_worldclim/PRISM_tmin_stable_4kmM2_200906_asc.asc",as.image=F)
tmin.jul<-readAsciiGrid("../culicoides/prism/prism_worldclim/PRISM_tmin_stable_4kmM2_200907_asc.asc",as.image=F)
tmin.aug<-readAsciiGrid("../culicoides/prism/prism_worldclim/PRISM_tmin_stable_4kmM2_200908_asc.asc",as.image=F)
tmin.sep<-readAsciiGrid("../culicoides/prism/prism_worldclim/PRISM_tmin_stable_4kmM2_200909_asc.asc",as.image=F)
tmin.oct<-readAsciiGrid("../culicoides/prism/prism_worldclim/PRISM_tmin_stable_4kmM2_200910_asc.asc",as.image=F)
tmin.nov<-readAsciiGrid("../culicoides/prism/prism_worldclim/PRISM_tmin_stable_4kmM2_200911_asc.asc",as.image=F)
tmin.dec<-readAsciiGrid("../culicoides/prism/prism_worldclim/PRISM_tmin_stable_4kmM2_200912_asc.asc",as.image=F)

tmax.jan<-readAsciiGrid("../culicoides/prism/prism_worldclim/PRISM_tmax_stable_4kmM2_200901_asc.asc",as.image=F)
tmax.feb<-readAsciiGrid("../culicoides/prism/prism_worldclim/PRISM_tmax_stable_4kmM2_200902_asc.asc",as.image=F)
tmax.mar<-readAsciiGrid("../culicoides/prism/prism_worldclim/PRISM_tmax_stable_4kmM2_200903_asc.asc",as.image=F)
tmax.apr<-readAsciiGrid("../culicoides/prism/prism_worldclim/PRISM_tmax_stable_4kmM2_200904_asc.asc",as.image=F)
tmax.may<-readAsciiGrid("../culicoides/prism/prism_worldclim/PRISM_tmax_stable_4kmM2_200905_asc.asc",as.image=F)
tmax.jun<-readAsciiGrid("../culicoides/prism/prism_worldclim/PRISM_tmax_stable_4kmM2_200906_asc.asc",as.image=F)
tmax.jul<-readAsciiGrid("../culicoides/prism/prism_worldclim/PRISM_tmax_stable_4kmM2_200907_asc.asc",as.image=F)
tmax.aug<-readAsciiGrid("../culicoides/prism/prism_worldclim/PRISM_tmax_stable_4kmM2_200908_asc.asc",as.image=F)
tmax.sep<-readAsciiGrid("../culicoides/prism/prism_worldclim/PRISM_tmax_stable_4kmM2_200909_asc.asc",as.image=F)
tmax.oct<-readAsciiGrid("../culicoides/prism/prism_worldclim/PRISM_tmax_stable_4kmM2_200910_asc.asc",as.image=F)
tmax.nov<-readAsciiGrid("../culicoides/prism/prism_worldclim/PRISM_tmax_stable_4kmM2_200911_asc.asc",as.image=F)
tmax.dec<-readAsciiGrid("../culicoides/prism/prism_worldclim/PRISM_tmax_stable_4kmM2_200912_asc.asc",as.image=F)

######### MIN TEMP ################
r.tmin.jan<- raster::raster(tmin.jan)
#r.tmin.jan<- raster::crop(r.tmin.jan,extent(c(-100,-80,24.5,43)))
prism.tmin.jan<- raster::extract(r.tmin.jan,cbind(sites$lon,sites$lat))
sites$prism.tmin.jan<-prism.tmin.jan

r.tmin.feb<- raster::raster(tmin.feb)
#r.tmin.feb<- raster::crop(r.tmin.feb,extent(c(-100,-80,24.5,43)))
prism.tmin.feb<- raster::extract(r.tmin.feb,cbind(sites$lon,sites$lat))
sites$prism.tmin.feb<-prism.tmin.feb

r.tmin.mar<- raster::raster(tmin.mar)
#r.tmin.mar<- raster::crop(r.tmin.mar,extent(c(-100,-80,24.5,43)))
prism.tmin.mar<- raster::extract(r.tmin.mar,cbind(sites$lon,sites$lat))
sites$prism.tmin.mar<-prism.tmin.mar

r.tmin.apr<- raster::raster(tmin.apr)
#r.tmin.apr<- raster::crop(r.tmin.apr,extent(c(-100,-80,24.5,43)))
prism.tmin.apr<- raster::extract(r.tmin.apr,cbind(sites$lon,sites$lat))
sites$prism.tmin.apr<-prism.tmin.apr

r.tmin.may<- raster::raster(tmin.may)
#r.tmin.may<- raster::crop(r.tmin.may,extent(c(-100,-80,24.5,43)))
prism.tmin.may<- raster::extract(r.tmin.may,cbind(sites$lon,sites$lat))
sites$prism.tmin.may<-prism.tmin.may

r.tmin.jun<- raster::raster(tmin.jun)
#r.tmin.jun<- raster::crop(r.tmin.jun,extent(c(-100,-80,24.5,43)))
prism.tmin.jun<- raster::extract(r.tmin.jun,cbind(sites$lon,sites$lat))
sites$prism.tmin.jun<-prism.tmin.jun

r.tmin.jul<- raster::raster(tmin.jul)
#r.tmin.jul<- raster::crop(r.tmin.jul,extent(c(-100,-80,24.5,43)))
prism.tmin.jul<- raster::extract(r.tmin.jul,cbind(sites$lon,sites$lat))
sites$prism.tmin.jul<-prism.tmin.jul

r.tmin.aug<- raster::raster(tmin.aug)
#r.tmin.aug<- raster::crop(r.tmin.aug,extent(c(-100,-80,24.5,43)))
prism.tmin.aug<- raster::extract(r.tmin.aug,cbind(sites$lon,sites$lat))
sites$prism.tmin.aug<-prism.tmin.aug

r.tmin.sep<- raster::raster(tmin.sep)
#r.tmin.sep<- raster::crop(r.tmin.sep,extent(c(-100,-80,24.5,43)))
prism.tmin.sep<- raster::extract(r.tmin.sep,cbind(sites$lon,sites$lat))
sites$prism.tmin.sep<-prism.tmin.sep

r.tmin.oct<- raster::raster(tmin.oct)
#r.tmin.oct<- raster::crop(r.tmin.oct,extent(c(-100,-80,24.5,43)))
prism.tmin.oct<- raster::extract(r.tmin.oct,cbind(sites$lon,sites$lat))
sites$prism.tmin.oct<-prism.tmin.oct

r.tmin.nov<- raster::raster(tmin.nov)
#r.tmin.nov<- raster::crop(r.tmin.nov,extent(c(-100,-80,24.5,43)))
prism.tmin.nov<- raster::extract(r.tmin.nov,cbind(sites$lon,sites$lat))
sites$prism.tmin.nov<-prism.tmin.nov

r.tmin.dec<- raster::raster(tmin.dec)
#r.tmin.dec<- raster::crop(r.tmin.dec,extent(c(-100,-80,24.5,43)))
prism.tmin.dec<- raster::extract(r.tmin.dec,cbind(sites$lon,sites$lat))
sites$prism.tmin.dec<-prism.tmin.dec

########## MAX TEMP ###########

r.tmax.jan<- raster::raster(tmax.jan)
r.tmax.jan<- raster::crop(r.tmax.jan,extent(c(-100,-80,24.5,43)))
prism.tmax.jan<- raster::extract(r.tmax.jan,cbind(sites$lon,sites$lat))
sites$prism.tmax.jan<-prism.tmax.jan

r.tmax.feb<- raster::raster(tmax.feb)
r.tmax.feb<- raster::crop(r.tmax.feb,extent(c(-100,-80,24.5,43)))
prism.tmax.feb<- raster::extract(r.tmax.feb,cbind(sites$lon,sites$lat))
sites$prism.tmax.feb<-prism.tmax.feb

r.tmax.mar<- raster::raster(tmax.mar)
r.tmax.mar<- raster::crop(r.tmax.mar,extent(c(-100,-80,24.5,43)))
prism.tmax.mar<- raster::extract(r.tmax.mar,cbind(sites$lon,sites$lat))
sites$prism.tmax.mar<-prism.tmax.mar

r.tmax.apr<- raster::raster(tmax.apr)
r.tmax.apr<- raster::crop(r.tmax.apr,extent(c(-100,-80,24.5,43)))
prism.tmax.apr<- raster::extract(r.tmax.apr,cbind(sites$lon,sites$lat))
sites$prism.tmax.apr<-prism.tmax.apr

r.tmax.may<- raster::raster(tmax.may)
r.tmax.may<- raster::crop(r.tmax.may,extent(c(-100,-80,24.5,43)))
prism.tmax.may<- raster::extract(r.tmax.may,cbind(sites$lon,sites$lat))
sites$prism.tmax.may<-prism.tmax.may

r.tmax.jun<- raster::raster(tmax.jun)
r.tmax.jun<- raster::crop(r.tmax.jun,extent(c(-100,-80,24.5,43)))
prism.tmax.jun<- raster::extract(r.tmax.jun,cbind(sites$lon,sites$lat))
sites$prism.tmax.jun<-prism.tmax.jun

r.tmax.jul<- raster::raster(tmax.jul)
r.tmax.jul<- raster::crop(r.tmax.jul,extent(c(-100,-80,24.5,43)))
prism.tmax.jul<- raster::extract(r.tmax.jul,cbind(sites$lon,sites$lat))
sites$prism.tmax.jul<-prism.tmax.jul

r.tmax.aug<- raster::raster(tmax.aug)
r.tmax.aug<- raster::crop(r.tmax.aug,extent(c(-100,-80,24.5,43)))
prism.tmax.aug<- raster::extract(r.tmax.aug,cbind(sites$lon,sites$lat))
sites$prism.tmax.aug<-prism.tmax.aug

r.tmax.sep<- raster::raster(tmax.sep)
r.tmax.sep<- raster::crop(r.tmax.sep,extent(c(-100,-80,24.5,43)))
prism.tmax.sep<- raster::extract(r.tmax.sep,cbind(sites$lon,sites$lat))
sites$prism.tmax.sep<-prism.tmax.sep

r.tmax.oct<- raster::raster(tmax.oct)
r.tmax.oct<- raster::crop(r.tmax.oct,extent(c(-100,-80,24.5,43)))
prism.tmax.oct<- raster::extract(r.tmax.oct,cbind(sites$lon,sites$lat))
sites$prism.tmax.oct<-prism.tmax.oct

r.tmax.nov<- raster::raster(tmax.nov)
r.tmax.nov<- raster::crop(r.tmax.nov,extent(c(-100,-80,24.5,43)))
prism.tmax.nov<- raster::extract(r.tmax.nov,cbind(sites$lon,sites$lat))
sites$prism.tmax.nov<-prism.tmax.nov

r.tmax.dec<- raster::raster(tmax.dec)
r.tmax.dec<- raster::crop(r.tmax.dec,extent(c(-100,-80,24.5,43)))
prism.tmax.dec<- raster::extract(r.tmax.dec,cbind(sites$lon,sites$lat))
sites$prism.tmax.dec<-prism.tmax.dec


sites$prism.tmin<-apply(sites[,which(names(sites)=="prism.tmin.jan"):which(names(sites)=="prism.tmin.dec")],1,min)
sites$prism.tmax<-apply(sites[,which(names(sites)=="prism.tmax.jan"):which(names(sites)=="prism.tmax.dec")],1,max)

############ CONSTRUCT ANNUAL TEMP RANGE ####################
sites$prism.trange<-sites$prism.tmax-sites$prism.tmin

```
